site_name: NATS Tower
site_description: A simple manager application for multi-tenancy in NATS
repo_url: https://github.com/nats-tower/nats-tower
docs_dir: docs

nav:
  - Home: 'index.md'
  - 'Getting started': 'getting_started/index.md'
  - 'Admin documentation':
    - 'Overview': 'admin_doc/index.md'
    - 'Installation': 'admin_doc/installation/index.md'
    - 'Configuration': 'admin_doc/configuration/index.md'
    - 'User management': 'admin_doc/user_management/index.md'
  - 'User documentation':
    - 'Overview': 'user_doc/index.md'
    - 'Accounts': 'user_doc/accounts/index.md'
    - 'Users': 'user_doc/users/index.md'

theme:
  name: material
  custom_dir: docs/overrides
  font: false
  palette:
    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.footer
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

extra:
  homepage: /
  generator: false
  analytics:
    provider: umami
markdown_extensions:
  - admonition
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
