port = 4224

jetstream {
    store_dir = "jetstream"
}

resolver: {
    type: full
    # Directory in which account jwt will be stored
    dir: './jwt'
    # In order to support jwt deletion, set to true
    # If the resolver type is full delete will rename the jwt.
    # This is to allow manual restoration in case of inadvertent deletion.
    # To restore a jwt, remove the added suffix .delete and restart or send a reload signal.
    # To free up storage you must manually delete files with the suffix .delete.
    allow_delete: true
    # Interval at which a nats-server with a nats based account resolver will compare
    # it's state with one random nats based account resolver in the cluster and if needed,
    # exchange jwt and converge on the same set of jwt.
    interval: "2m"
    # limit on the number of jwt stored, will reject new jwt once limit is hit.
    limit: 1000
}

# DEV credentials, do not use in production

operator = eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJaVUpYT1JaM1RPM0FOQ0NBWlRIN0w1REFZVVBKQ1FRTlk0UlUzWFBER1hUQlVVRVE0UlVRIiwiaWF0IjoxNzQzMDgwNzUzLCJpc3MiOiJPRFlBSkI0QVpKRFNMQzczREhZWk40WVk0VDJQNjJMRkQzQTJKNExLSjNTU1FUWU9NSldWUE0zWSIsInN1YiI6Ik9EWUFKQjRBWkpEU0xDNzNESFlaTjRZWTRUMlA2MkxGRDNBMko0TEtKM1NTUVRZT01KV1ZQTTNZIiwibmF0cyI6eyJzaWduaW5nX2tleXMiOlsiT0Q2RTNKRkM3RVlYUkRST1hNUFRJMllHSkhUUFM0TDVVRTVPUVo3M0RRR1RWVUFPREhUVkNSN1ciXSwidHlwZSI6Im9wZXJhdG9yIiwidmVyc2lvbiI6Mn19.P5sRju5oH2CoFWOYhhceWiMoX66qe9st4bpdLkRlb7Zt7qQrWbDFWMmcx4Dy4lIufwJ6bbVdkl_oDdnvlGX2DA

system_account = ABKILWUE3SUBDPFPFMKHN24CL2EQ7QZ6VQ7TXXM2BDZJA7OFUGGVOUB3

resolver_preload = {
  ABKILWUE3SUBDPFPFMKHN24CL2EQ7QZ6VQ7TXXM2BDZJA7OFUGGVOUB3: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJCS0I2N1dOMlY0WEtXNlY0UFNKQk9UUkVYQUhBWE1ISTJFSkpKMzQ2REY0VkVCTlBOVDZRIiwiaWF0IjoxNzQzMDgwNzUzLCJpc3MiOiJPRDZFM0pGQzdFWVhSRFJPWE1QVEkyWUdKSFRQUzRMNVVFNU9RWjczRFFHVFZVQU9ESFRWQ1I3VyIsIm5hbWUiOiJTWVMiLCJzdWIiOiJBQktJTFdVRTNTVUJEUEZQRk1LSE4yNENMMkVRN1FaNlZRN1RYWE0yQkRaSkE3T0ZVR0dWT1VCMyIsIm5hdHMiOnsiZXhwb3J0cyI6W3sibmFtZSI6ImFjY291bnQtbW9uaXRvcmluZy1zdHJlYW1zIiwic3ViamVjdCI6IiRTWVMuQUNDT1VOVC4qLlx1MDAzZSIsInR5cGUiOiJzdHJlYW0iLCJhY2NvdW50X3Rva2VuX3Bvc2l0aW9uIjozLCJkZXNjcmlwdGlvbiI6IkFjY291bnQgc3BlY2lmaWMgbW9uaXRvcmluZyBzdHJlYW0iLCJpbmZvX3VybCI6Imh0dHBzOi8vZG9jcy5uYXRzLmlvL25hdHMtc2VydmVyL2NvbmZpZ3VyYXRpb24vc3lzX2FjY291bnRzIn0seyJuYW1lIjoiYWNjb3VudC1tb25pdG9yaW5nLXNlcnZpY2VzIiwic3ViamVjdCI6IiRTWVMuUkVRLkFDQ09VTlQuKi4qIiwidHlwZSI6InNlcnZpY2UiLCJyZXNwb25zZV90eXBlIjoiU3RyZWFtIiwiYWNjb3VudF90b2tlbl9wb3NpdGlvbiI6NCwiZGVzY3JpcHRpb24iOiJSZXF1ZXN0IGFjY291bnQgc3BlY2lmaWMgbW9uaXRvcmluZyBzZXJ2aWNlcyBmb3I6IFNVQlNaLCBDT05OWiwgTEVBRlosIEpTWiBhbmQgSU5GTyIsImluZm9fdXJsIjoiaHR0cHM6Ly9kb2NzLm5hdHMuaW8vbmF0cy1zZXJ2ZXIvY29uZmlndXJhdGlvbi9zeXNfYWNjb3VudHMifV0sImxpbWl0cyI6eyJzdWJzIjotMSwiZGF0YSI6LTEsInBheWxvYWQiOi0xLCJpbXBvcnRzIjotMSwiZXhwb3J0cyI6LTEsIndpbGRjYXJkcyI6dHJ1ZSwiY29ubiI6LTEsImxlYWYiOi0xfSwic2lnbmluZ19rZXlzIjpbIkFCVUlKU1pXNjVHRklFNEJWMkwzM1REWFVSQTRVR0tPTkMyWVBGUUNYUzRUTFhDT1REWFBVT0tSIl0sImRlZmF1bHRfcGVybWlzc2lvbnMiOnsicHViIjp7fSwic3ViIjp7fX0sImF1dGhvcml6YXRpb24iOnt9LCJ0eXBlIjoiYWNjb3VudCIsInZlcnNpb24iOjJ9fQ.hCNhwahZINO1HLetr4KC_iJ8SBVuTavmef4XU_cfP6yV5s2BVY2Y4YXURYgF2Ix0QjorMEIHOJkG0MNybsfcBQ
}
