/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './pages/__root'
import { Route as AppRouteImport } from './pages/_app'
import { Route as AppInstallationsInstallationIdRouteImport } from './pages/_app/installations/$installationId'

const SigninLazyRouteImport = createFileRoute('/signin')()
const AppIndexLazyRouteImport = createFileRoute('/_app/')()
const AppInstallationsIndexLazyRouteImport = createFileRoute(
  '/_app/installations/',
)()
const AppInstallationsInstallationIdLimitsIndexLazyRouteImport =
  createFileRoute('/_app/installations_/$installationId/limits/')()
const AppInstallationsInstallationIdClusterStateIndexLazyRouteImport =
  createFileRoute('/_app/installations_/$installationId/cluster-state/')()
const AppInstallationsInstallationIdAccountsIndexLazyRouteImport =
  createFileRoute('/_app/installations_/$installationId/accounts/')()
const AppInstallationsInstallationIdAccountsAccountIdUsersIndexLazyRouteImport =
  createFileRoute(
    '/_app/installations_/$installationId/accounts_/$accountId/users/',
  )()
const AppInstallationsInstallationIdAccountsAccountIdRolesIndexLazyRouteImport =
  createFileRoute(
    '/_app/installations_/$installationId/accounts_/$accountId/roles/',
  )()
const AppInstallationsInstallationIdAccountsAccountIdK8sAccessIndexLazyRouteImport =
  createFileRoute(
    '/_app/installations_/$installationId/accounts_/$accountId/k8s-access/',
  )()
const AppInstallationsInstallationIdAccountsAccountIdInfoIndexLazyRouteImport =
  createFileRoute(
    '/_app/installations_/$installationId/accounts_/$accountId/info/',
  )()
const AppInstallationsInstallationIdAccountsAccountIdImportsIndexLazyRouteImport =
  createFileRoute(
    '/_app/installations_/$installationId/accounts_/$accountId/imports/',
  )()
const AppInstallationsInstallationIdAccountsAccountIdExportsIndexLazyRouteImport =
  createFileRoute(
    '/_app/installations_/$installationId/accounts_/$accountId/exports/',
  )()

const SigninLazyRoute = SigninLazyRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./pages/signin.lazy').then((d) => d.Route))
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexLazyRoute = AppIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./pages/_app/index.lazy').then((d) => d.Route))
const AppInstallationsIndexLazyRoute =
  AppInstallationsIndexLazyRouteImport.update({
    id: '/installations/',
    path: '/installations/',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./pages/_app/installations/index.lazy').then((d) => d.Route),
  )
const AppInstallationsInstallationIdRoute =
  AppInstallationsInstallationIdRouteImport.update({
    id: '/installations/$installationId',
    path: '/installations/$installationId',
    getParentRoute: () => AppRoute,
  } as any)
const AppInstallationsInstallationIdLimitsIndexLazyRoute =
  AppInstallationsInstallationIdLimitsIndexLazyRouteImport.update({
    id: '/installations_/$installationId/limits/',
    path: '/installations/$installationId/limits/',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./pages/_app/installations_/$installationId/limits/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AppInstallationsInstallationIdClusterStateIndexLazyRoute =
  AppInstallationsInstallationIdClusterStateIndexLazyRouteImport.update({
    id: '/installations_/$installationId/cluster-state/',
    path: '/installations/$installationId/cluster-state/',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./pages/_app/installations_/$installationId/cluster-state/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AppInstallationsInstallationIdAccountsIndexLazyRoute =
  AppInstallationsInstallationIdAccountsIndexLazyRouteImport.update({
    id: '/installations_/$installationId/accounts/',
    path: '/installations/$installationId/accounts/',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./pages/_app/installations_/$installationId/accounts/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AppInstallationsInstallationIdAccountsAccountIdUsersIndexLazyRoute =
  AppInstallationsInstallationIdAccountsAccountIdUsersIndexLazyRouteImport.update(
    {
      id: '/installations_/$installationId/accounts_/$accountId/users/',
      path: '/installations/$installationId/accounts/$accountId/users/',
      getParentRoute: () => AppRoute,
    } as any,
  ).lazy(() =>
    import('./pages/_app/installations_/$installationId/accounts_/$accountId/users/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AppInstallationsInstallationIdAccountsAccountIdRolesIndexLazyRoute =
  AppInstallationsInstallationIdAccountsAccountIdRolesIndexLazyRouteImport.update(
    {
      id: '/installations_/$installationId/accounts_/$accountId/roles/',
      path: '/installations/$installationId/accounts/$accountId/roles/',
      getParentRoute: () => AppRoute,
    } as any,
  ).lazy(() =>
    import('./pages/_app/installations_/$installationId/accounts_/$accountId/roles/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AppInstallationsInstallationIdAccountsAccountIdK8sAccessIndexLazyRoute =
  AppInstallationsInstallationIdAccountsAccountIdK8sAccessIndexLazyRouteImport.update(
    {
      id: '/installations_/$installationId/accounts_/$accountId/k8s-access/',
      path: '/installations/$installationId/accounts/$accountId/k8s-access/',
      getParentRoute: () => AppRoute,
    } as any,
  ).lazy(() =>
    import('./pages/_app/installations_/$installationId/accounts_/$accountId/k8s-access/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AppInstallationsInstallationIdAccountsAccountIdInfoIndexLazyRoute =
  AppInstallationsInstallationIdAccountsAccountIdInfoIndexLazyRouteImport.update(
    {
      id: '/installations_/$installationId/accounts_/$accountId/info/',
      path: '/installations/$installationId/accounts/$accountId/info/',
      getParentRoute: () => AppRoute,
    } as any,
  ).lazy(() =>
    import('./pages/_app/installations_/$installationId/accounts_/$accountId/info/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AppInstallationsInstallationIdAccountsAccountIdImportsIndexLazyRoute =
  AppInstallationsInstallationIdAccountsAccountIdImportsIndexLazyRouteImport.update(
    {
      id: '/installations_/$installationId/accounts_/$accountId/imports/',
      path: '/installations/$installationId/accounts/$accountId/imports/',
      getParentRoute: () => AppRoute,
    } as any,
  ).lazy(() =>
    import('./pages/_app/installations_/$installationId/accounts_/$accountId/imports/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AppInstallationsInstallationIdAccountsAccountIdExportsIndexLazyRoute =
  AppInstallationsInstallationIdAccountsAccountIdExportsIndexLazyRouteImport.update(
    {
      id: '/installations_/$installationId/accounts_/$accountId/exports/',
      path: '/installations/$installationId/accounts/$accountId/exports/',
      getParentRoute: () => AppRoute,
    } as any,
  ).lazy(() =>
    import('./pages/_app/installations_/$installationId/accounts_/$accountId/exports/index.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof AppIndexLazyRoute
  '/signin': typeof SigninLazyRoute
  '/installations/$installationId': typeof AppInstallationsInstallationIdRoute
  '/installations/': typeof AppInstallationsIndexLazyRoute
  '/installations/$installationId/accounts/': typeof AppInstallationsInstallationIdAccountsIndexLazyRoute
  '/installations/$installationId/cluster-state/': typeof AppInstallationsInstallationIdClusterStateIndexLazyRoute
  '/installations/$installationId/limits/': typeof AppInstallationsInstallationIdLimitsIndexLazyRoute
  '/installations/$installationId/accounts/$accountId/exports/': typeof AppInstallationsInstallationIdAccountsAccountIdExportsIndexLazyRoute
  '/installations/$installationId/accounts/$accountId/imports/': typeof AppInstallationsInstallationIdAccountsAccountIdImportsIndexLazyRoute
  '/installations/$installationId/accounts/$accountId/info/': typeof AppInstallationsInstallationIdAccountsAccountIdInfoIndexLazyRoute
  '/installations/$installationId/accounts/$accountId/k8s-access/': typeof AppInstallationsInstallationIdAccountsAccountIdK8sAccessIndexLazyRoute
  '/installations/$installationId/accounts/$accountId/roles/': typeof AppInstallationsInstallationIdAccountsAccountIdRolesIndexLazyRoute
  '/installations/$installationId/accounts/$accountId/users/': typeof AppInstallationsInstallationIdAccountsAccountIdUsersIndexLazyRoute
}
export interface FileRoutesByTo {
  '/signin': typeof SigninLazyRoute
  '/': typeof AppIndexLazyRoute
  '/installations/$installationId': typeof AppInstallationsInstallationIdRoute
  '/installations': typeof AppInstallationsIndexLazyRoute
  '/installations/$installationId/accounts': typeof AppInstallationsInstallationIdAccountsIndexLazyRoute
  '/installations/$installationId/cluster-state': typeof AppInstallationsInstallationIdClusterStateIndexLazyRoute
  '/installations/$installationId/limits': typeof AppInstallationsInstallationIdLimitsIndexLazyRoute
  '/installations/$installationId/accounts/$accountId/exports': typeof AppInstallationsInstallationIdAccountsAccountIdExportsIndexLazyRoute
  '/installations/$installationId/accounts/$accountId/imports': typeof AppInstallationsInstallationIdAccountsAccountIdImportsIndexLazyRoute
  '/installations/$installationId/accounts/$accountId/info': typeof AppInstallationsInstallationIdAccountsAccountIdInfoIndexLazyRoute
  '/installations/$installationId/accounts/$accountId/k8s-access': typeof AppInstallationsInstallationIdAccountsAccountIdK8sAccessIndexLazyRoute
  '/installations/$installationId/accounts/$accountId/roles': typeof AppInstallationsInstallationIdAccountsAccountIdRolesIndexLazyRoute
  '/installations/$installationId/accounts/$accountId/users': typeof AppInstallationsInstallationIdAccountsAccountIdUsersIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/signin': typeof SigninLazyRoute
  '/_app/': typeof AppIndexLazyRoute
  '/_app/installations/$installationId': typeof AppInstallationsInstallationIdRoute
  '/_app/installations/': typeof AppInstallationsIndexLazyRoute
  '/_app/installations_/$installationId/accounts/': typeof AppInstallationsInstallationIdAccountsIndexLazyRoute
  '/_app/installations_/$installationId/cluster-state/': typeof AppInstallationsInstallationIdClusterStateIndexLazyRoute
  '/_app/installations_/$installationId/limits/': typeof AppInstallationsInstallationIdLimitsIndexLazyRoute
  '/_app/installations_/$installationId/accounts_/$accountId/exports/': typeof AppInstallationsInstallationIdAccountsAccountIdExportsIndexLazyRoute
  '/_app/installations_/$installationId/accounts_/$accountId/imports/': typeof AppInstallationsInstallationIdAccountsAccountIdImportsIndexLazyRoute
  '/_app/installations_/$installationId/accounts_/$accountId/info/': typeof AppInstallationsInstallationIdAccountsAccountIdInfoIndexLazyRoute
  '/_app/installations_/$installationId/accounts_/$accountId/k8s-access/': typeof AppInstallationsInstallationIdAccountsAccountIdK8sAccessIndexLazyRoute
  '/_app/installations_/$installationId/accounts_/$accountId/roles/': typeof AppInstallationsInstallationIdAccountsAccountIdRolesIndexLazyRoute
  '/_app/installations_/$installationId/accounts_/$accountId/users/': typeof AppInstallationsInstallationIdAccountsAccountIdUsersIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/installations/$installationId'
    | '/installations/'
    | '/installations/$installationId/accounts/'
    | '/installations/$installationId/cluster-state/'
    | '/installations/$installationId/limits/'
    | '/installations/$installationId/accounts/$accountId/exports/'
    | '/installations/$installationId/accounts/$accountId/imports/'
    | '/installations/$installationId/accounts/$accountId/info/'
    | '/installations/$installationId/accounts/$accountId/k8s-access/'
    | '/installations/$installationId/accounts/$accountId/roles/'
    | '/installations/$installationId/accounts/$accountId/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/'
    | '/installations/$installationId'
    | '/installations'
    | '/installations/$installationId/accounts'
    | '/installations/$installationId/cluster-state'
    | '/installations/$installationId/limits'
    | '/installations/$installationId/accounts/$accountId/exports'
    | '/installations/$installationId/accounts/$accountId/imports'
    | '/installations/$installationId/accounts/$accountId/info'
    | '/installations/$installationId/accounts/$accountId/k8s-access'
    | '/installations/$installationId/accounts/$accountId/roles'
    | '/installations/$installationId/accounts/$accountId/users'
  id:
    | '__root__'
    | '/_app'
    | '/signin'
    | '/_app/'
    | '/_app/installations/$installationId'
    | '/_app/installations/'
    | '/_app/installations_/$installationId/accounts/'
    | '/_app/installations_/$installationId/cluster-state/'
    | '/_app/installations_/$installationId/limits/'
    | '/_app/installations_/$installationId/accounts_/$accountId/exports/'
    | '/_app/installations_/$installationId/accounts_/$accountId/imports/'
    | '/_app/installations_/$installationId/accounts_/$accountId/info/'
    | '/_app/installations_/$installationId/accounts_/$accountId/k8s-access/'
    | '/_app/installations_/$installationId/accounts_/$accountId/roles/'
    | '/_app/installations_/$installationId/accounts_/$accountId/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SigninLazyRoute: typeof SigninLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/installations/': {
      id: '/_app/installations/'
      path: '/installations'
      fullPath: '/installations/'
      preLoaderRoute: typeof AppInstallationsIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/installations/$installationId': {
      id: '/_app/installations/$installationId'
      path: '/installations/$installationId'
      fullPath: '/installations/$installationId'
      preLoaderRoute: typeof AppInstallationsInstallationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/installations_/$installationId/limits/': {
      id: '/_app/installations_/$installationId/limits/'
      path: '/installations/$installationId/limits'
      fullPath: '/installations/$installationId/limits/'
      preLoaderRoute: typeof AppInstallationsInstallationIdLimitsIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/installations_/$installationId/cluster-state/': {
      id: '/_app/installations_/$installationId/cluster-state/'
      path: '/installations/$installationId/cluster-state'
      fullPath: '/installations/$installationId/cluster-state/'
      preLoaderRoute: typeof AppInstallationsInstallationIdClusterStateIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/installations_/$installationId/accounts/': {
      id: '/_app/installations_/$installationId/accounts/'
      path: '/installations/$installationId/accounts'
      fullPath: '/installations/$installationId/accounts/'
      preLoaderRoute: typeof AppInstallationsInstallationIdAccountsIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/installations_/$installationId/accounts_/$accountId/users/': {
      id: '/_app/installations_/$installationId/accounts_/$accountId/users/'
      path: '/installations/$installationId/accounts/$accountId/users'
      fullPath: '/installations/$installationId/accounts/$accountId/users/'
      preLoaderRoute: typeof AppInstallationsInstallationIdAccountsAccountIdUsersIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/installations_/$installationId/accounts_/$accountId/roles/': {
      id: '/_app/installations_/$installationId/accounts_/$accountId/roles/'
      path: '/installations/$installationId/accounts/$accountId/roles'
      fullPath: '/installations/$installationId/accounts/$accountId/roles/'
      preLoaderRoute: typeof AppInstallationsInstallationIdAccountsAccountIdRolesIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/installations_/$installationId/accounts_/$accountId/k8s-access/': {
      id: '/_app/installations_/$installationId/accounts_/$accountId/k8s-access/'
      path: '/installations/$installationId/accounts/$accountId/k8s-access'
      fullPath: '/installations/$installationId/accounts/$accountId/k8s-access/'
      preLoaderRoute: typeof AppInstallationsInstallationIdAccountsAccountIdK8sAccessIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/installations_/$installationId/accounts_/$accountId/info/': {
      id: '/_app/installations_/$installationId/accounts_/$accountId/info/'
      path: '/installations/$installationId/accounts/$accountId/info'
      fullPath: '/installations/$installationId/accounts/$accountId/info/'
      preLoaderRoute: typeof AppInstallationsInstallationIdAccountsAccountIdInfoIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/installations_/$installationId/accounts_/$accountId/imports/': {
      id: '/_app/installations_/$installationId/accounts_/$accountId/imports/'
      path: '/installations/$installationId/accounts/$accountId/imports'
      fullPath: '/installations/$installationId/accounts/$accountId/imports/'
      preLoaderRoute: typeof AppInstallationsInstallationIdAccountsAccountIdImportsIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/installations_/$installationId/accounts_/$accountId/exports/': {
      id: '/_app/installations_/$installationId/accounts_/$accountId/exports/'
      path: '/installations/$installationId/accounts/$accountId/exports'
      fullPath: '/installations/$installationId/accounts/$accountId/exports/'
      preLoaderRoute: typeof AppInstallationsInstallationIdAccountsAccountIdExportsIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexLazyRoute: typeof AppIndexLazyRoute
  AppInstallationsInstallationIdRoute: typeof AppInstallationsInstallationIdRoute
  AppInstallationsIndexLazyRoute: typeof AppInstallationsIndexLazyRoute
  AppInstallationsInstallationIdAccountsIndexLazyRoute: typeof AppInstallationsInstallationIdAccountsIndexLazyRoute
  AppInstallationsInstallationIdClusterStateIndexLazyRoute: typeof AppInstallationsInstallationIdClusterStateIndexLazyRoute
  AppInstallationsInstallationIdLimitsIndexLazyRoute: typeof AppInstallationsInstallationIdLimitsIndexLazyRoute
  AppInstallationsInstallationIdAccountsAccountIdExportsIndexLazyRoute: typeof AppInstallationsInstallationIdAccountsAccountIdExportsIndexLazyRoute
  AppInstallationsInstallationIdAccountsAccountIdImportsIndexLazyRoute: typeof AppInstallationsInstallationIdAccountsAccountIdImportsIndexLazyRoute
  AppInstallationsInstallationIdAccountsAccountIdInfoIndexLazyRoute: typeof AppInstallationsInstallationIdAccountsAccountIdInfoIndexLazyRoute
  AppInstallationsInstallationIdAccountsAccountIdK8sAccessIndexLazyRoute: typeof AppInstallationsInstallationIdAccountsAccountIdK8sAccessIndexLazyRoute
  AppInstallationsInstallationIdAccountsAccountIdRolesIndexLazyRoute: typeof AppInstallationsInstallationIdAccountsAccountIdRolesIndexLazyRoute
  AppInstallationsInstallationIdAccountsAccountIdUsersIndexLazyRoute: typeof AppInstallationsInstallationIdAccountsAccountIdUsersIndexLazyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexLazyRoute: AppIndexLazyRoute,
  AppInstallationsInstallationIdRoute: AppInstallationsInstallationIdRoute,
  AppInstallationsIndexLazyRoute: AppInstallationsIndexLazyRoute,
  AppInstallationsInstallationIdAccountsIndexLazyRoute:
    AppInstallationsInstallationIdAccountsIndexLazyRoute,
  AppInstallationsInstallationIdClusterStateIndexLazyRoute:
    AppInstallationsInstallationIdClusterStateIndexLazyRoute,
  AppInstallationsInstallationIdLimitsIndexLazyRoute:
    AppInstallationsInstallationIdLimitsIndexLazyRoute,
  AppInstallationsInstallationIdAccountsAccountIdExportsIndexLazyRoute:
    AppInstallationsInstallationIdAccountsAccountIdExportsIndexLazyRoute,
  AppInstallationsInstallationIdAccountsAccountIdImportsIndexLazyRoute:
    AppInstallationsInstallationIdAccountsAccountIdImportsIndexLazyRoute,
  AppInstallationsInstallationIdAccountsAccountIdInfoIndexLazyRoute:
    AppInstallationsInstallationIdAccountsAccountIdInfoIndexLazyRoute,
  AppInstallationsInstallationIdAccountsAccountIdK8sAccessIndexLazyRoute:
    AppInstallationsInstallationIdAccountsAccountIdK8sAccessIndexLazyRoute,
  AppInstallationsInstallationIdAccountsAccountIdRolesIndexLazyRoute:
    AppInstallationsInstallationIdAccountsAccountIdRolesIndexLazyRoute,
  AppInstallationsInstallationIdAccountsAccountIdUsersIndexLazyRoute:
    AppInstallationsInstallationIdAccountsAccountIdUsersIndexLazyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SigninLazyRoute: SigninLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
