/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as AppImport } from './pages/_app'
import { Route as AppInstallationsInstallationIdImport } from './pages/_app/installations/$installationId'

// Create Virtual Routes

const SigninLazyImport = createFileRoute('/signin')()
const AppIndexLazyImport = createFileRoute('/_app/')()
const AppInstallationsIndexLazyImport = createFileRoute(
  '/_app/installations/',
)()
const AppInstallationsInstallationIdLimitsIndexLazyImport = createFileRoute(
  '/_app/installations_/$installationId/limits/',
)()
const AppInstallationsInstallationIdAccountsIndexLazyImport = createFileRoute(
  '/_app/installations_/$installationId/accounts/',
)()
const AppInstallationsInstallationIdAccountsAccountIdUsersIndexLazyImport =
  createFileRoute(
    '/_app/installations_/$installationId/accounts_/$accountId/users/',
  )()
const AppInstallationsInstallationIdAccountsAccountIdK8sAccessIndexLazyImport =
  createFileRoute(
    '/_app/installations_/$installationId/accounts_/$accountId/k8s-access/',
  )()

// Create/Update Routes

const SigninLazyRoute = SigninLazyImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/signin.lazy').then((d) => d.Route))

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexLazyRoute = AppIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./pages/_app/index.lazy').then((d) => d.Route))

const AppInstallationsIndexLazyRoute = AppInstallationsIndexLazyImport.update({
  id: '/installations/',
  path: '/installations/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./pages/_app/installations/index.lazy').then((d) => d.Route),
)

const AppInstallationsInstallationIdRoute =
  AppInstallationsInstallationIdImport.update({
    id: '/installations/$installationId',
    path: '/installations/$installationId',
    getParentRoute: () => AppRoute,
  } as any)

const AppInstallationsInstallationIdLimitsIndexLazyRoute =
  AppInstallationsInstallationIdLimitsIndexLazyImport.update({
    id: '/installations_/$installationId/limits/',
    path: '/installations/$installationId/limits/',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import(
      './pages/_app/installations_/$installationId/limits/index.lazy'
    ).then((d) => d.Route),
  )

const AppInstallationsInstallationIdAccountsIndexLazyRoute =
  AppInstallationsInstallationIdAccountsIndexLazyImport.update({
    id: '/installations_/$installationId/accounts/',
    path: '/installations/$installationId/accounts/',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import(
      './pages/_app/installations_/$installationId/accounts/index.lazy'
    ).then((d) => d.Route),
  )

const AppInstallationsInstallationIdAccountsAccountIdUsersIndexLazyRoute =
  AppInstallationsInstallationIdAccountsAccountIdUsersIndexLazyImport.update({
    id: '/installations_/$installationId/accounts_/$accountId/users/',
    path: '/installations/$installationId/accounts/$accountId/users/',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import(
      './pages/_app/installations_/$installationId/accounts_/$accountId/users/index.lazy'
    ).then((d) => d.Route),
  )

const AppInstallationsInstallationIdAccountsAccountIdK8sAccessIndexLazyRoute =
  AppInstallationsInstallationIdAccountsAccountIdK8sAccessIndexLazyImport.update(
    {
      id: '/installations_/$installationId/accounts_/$accountId/k8s-access/',
      path: '/installations/$installationId/accounts/$accountId/k8s-access/',
      getParentRoute: () => AppRoute,
    } as any,
  ).lazy(() =>
    import(
      './pages/_app/installations_/$installationId/accounts_/$accountId/k8s-access/index.lazy'
    ).then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninLazyImport
      parentRoute: typeof rootRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/installations/$installationId': {
      id: '/_app/installations/$installationId'
      path: '/installations/$installationId'
      fullPath: '/installations/$installationId'
      preLoaderRoute: typeof AppInstallationsInstallationIdImport
      parentRoute: typeof AppImport
    }
    '/_app/installations/': {
      id: '/_app/installations/'
      path: '/installations'
      fullPath: '/installations'
      preLoaderRoute: typeof AppInstallationsIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/installations_/$installationId/accounts/': {
      id: '/_app/installations_/$installationId/accounts/'
      path: '/installations/$installationId/accounts'
      fullPath: '/installations/$installationId/accounts'
      preLoaderRoute: typeof AppInstallationsInstallationIdAccountsIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/installations_/$installationId/limits/': {
      id: '/_app/installations_/$installationId/limits/'
      path: '/installations/$installationId/limits'
      fullPath: '/installations/$installationId/limits'
      preLoaderRoute: typeof AppInstallationsInstallationIdLimitsIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/installations_/$installationId/accounts_/$accountId/k8s-access/': {
      id: '/_app/installations_/$installationId/accounts_/$accountId/k8s-access/'
      path: '/installations/$installationId/accounts/$accountId/k8s-access'
      fullPath: '/installations/$installationId/accounts/$accountId/k8s-access'
      preLoaderRoute: typeof AppInstallationsInstallationIdAccountsAccountIdK8sAccessIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/installations_/$installationId/accounts_/$accountId/users/': {
      id: '/_app/installations_/$installationId/accounts_/$accountId/users/'
      path: '/installations/$installationId/accounts/$accountId/users'
      fullPath: '/installations/$installationId/accounts/$accountId/users'
      preLoaderRoute: typeof AppInstallationsInstallationIdAccountsAccountIdUsersIndexLazyImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppIndexLazyRoute: typeof AppIndexLazyRoute
  AppInstallationsInstallationIdRoute: typeof AppInstallationsInstallationIdRoute
  AppInstallationsIndexLazyRoute: typeof AppInstallationsIndexLazyRoute
  AppInstallationsInstallationIdAccountsIndexLazyRoute: typeof AppInstallationsInstallationIdAccountsIndexLazyRoute
  AppInstallationsInstallationIdLimitsIndexLazyRoute: typeof AppInstallationsInstallationIdLimitsIndexLazyRoute
  AppInstallationsInstallationIdAccountsAccountIdK8sAccessIndexLazyRoute: typeof AppInstallationsInstallationIdAccountsAccountIdK8sAccessIndexLazyRoute
  AppInstallationsInstallationIdAccountsAccountIdUsersIndexLazyRoute: typeof AppInstallationsInstallationIdAccountsAccountIdUsersIndexLazyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexLazyRoute: AppIndexLazyRoute,
  AppInstallationsInstallationIdRoute: AppInstallationsInstallationIdRoute,
  AppInstallationsIndexLazyRoute: AppInstallationsIndexLazyRoute,
  AppInstallationsInstallationIdAccountsIndexLazyRoute:
    AppInstallationsInstallationIdAccountsIndexLazyRoute,
  AppInstallationsInstallationIdLimitsIndexLazyRoute:
    AppInstallationsInstallationIdLimitsIndexLazyRoute,
  AppInstallationsInstallationIdAccountsAccountIdK8sAccessIndexLazyRoute:
    AppInstallationsInstallationIdAccountsAccountIdK8sAccessIndexLazyRoute,
  AppInstallationsInstallationIdAccountsAccountIdUsersIndexLazyRoute:
    AppInstallationsInstallationIdAccountsAccountIdUsersIndexLazyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AppRouteWithChildren
  '/signin': typeof SigninLazyRoute
  '/': typeof AppIndexLazyRoute
  '/installations/$installationId': typeof AppInstallationsInstallationIdRoute
  '/installations': typeof AppInstallationsIndexLazyRoute
  '/installations/$installationId/accounts': typeof AppInstallationsInstallationIdAccountsIndexLazyRoute
  '/installations/$installationId/limits': typeof AppInstallationsInstallationIdLimitsIndexLazyRoute
  '/installations/$installationId/accounts/$accountId/k8s-access': typeof AppInstallationsInstallationIdAccountsAccountIdK8sAccessIndexLazyRoute
  '/installations/$installationId/accounts/$accountId/users': typeof AppInstallationsInstallationIdAccountsAccountIdUsersIndexLazyRoute
}

export interface FileRoutesByTo {
  '/signin': typeof SigninLazyRoute
  '/': typeof AppIndexLazyRoute
  '/installations/$installationId': typeof AppInstallationsInstallationIdRoute
  '/installations': typeof AppInstallationsIndexLazyRoute
  '/installations/$installationId/accounts': typeof AppInstallationsInstallationIdAccountsIndexLazyRoute
  '/installations/$installationId/limits': typeof AppInstallationsInstallationIdLimitsIndexLazyRoute
  '/installations/$installationId/accounts/$accountId/k8s-access': typeof AppInstallationsInstallationIdAccountsAccountIdK8sAccessIndexLazyRoute
  '/installations/$installationId/accounts/$accountId/users': typeof AppInstallationsInstallationIdAccountsAccountIdUsersIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/signin': typeof SigninLazyRoute
  '/_app/': typeof AppIndexLazyRoute
  '/_app/installations/$installationId': typeof AppInstallationsInstallationIdRoute
  '/_app/installations/': typeof AppInstallationsIndexLazyRoute
  '/_app/installations_/$installationId/accounts/': typeof AppInstallationsInstallationIdAccountsIndexLazyRoute
  '/_app/installations_/$installationId/limits/': typeof AppInstallationsInstallationIdLimitsIndexLazyRoute
  '/_app/installations_/$installationId/accounts_/$accountId/k8s-access/': typeof AppInstallationsInstallationIdAccountsAccountIdK8sAccessIndexLazyRoute
  '/_app/installations_/$installationId/accounts_/$accountId/users/': typeof AppInstallationsInstallationIdAccountsAccountIdUsersIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/signin'
    | '/'
    | '/installations/$installationId'
    | '/installations'
    | '/installations/$installationId/accounts'
    | '/installations/$installationId/limits'
    | '/installations/$installationId/accounts/$accountId/k8s-access'
    | '/installations/$installationId/accounts/$accountId/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/'
    | '/installations/$installationId'
    | '/installations'
    | '/installations/$installationId/accounts'
    | '/installations/$installationId/limits'
    | '/installations/$installationId/accounts/$accountId/k8s-access'
    | '/installations/$installationId/accounts/$accountId/users'
  id:
    | '__root__'
    | '/_app'
    | '/signin'
    | '/_app/'
    | '/_app/installations/$installationId'
    | '/_app/installations/'
    | '/_app/installations_/$installationId/accounts/'
    | '/_app/installations_/$installationId/limits/'
    | '/_app/installations_/$installationId/accounts_/$accountId/k8s-access/'
    | '/_app/installations_/$installationId/accounts_/$accountId/users/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SigninLazyRoute: typeof SigninLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SigninLazyRoute: SigninLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/signin"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/",
        "/_app/installations/$installationId",
        "/_app/installations/",
        "/_app/installations_/$installationId/accounts/",
        "/_app/installations_/$installationId/limits/",
        "/_app/installations_/$installationId/accounts_/$accountId/k8s-access/",
        "/_app/installations_/$installationId/accounts_/$accountId/users/"
      ]
    },
    "/signin": {
      "filePath": "signin.lazy.tsx"
    },
    "/_app/": {
      "filePath": "_app/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/installations/$installationId": {
      "filePath": "_app/installations/$installationId.tsx",
      "parent": "/_app"
    },
    "/_app/installations/": {
      "filePath": "_app/installations/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/installations_/$installationId/accounts/": {
      "filePath": "_app/installations_/$installationId/accounts/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/installations_/$installationId/limits/": {
      "filePath": "_app/installations_/$installationId/limits/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/installations_/$installationId/accounts_/$accountId/k8s-access/": {
      "filePath": "_app/installations_/$installationId/accounts_/$accountId/k8s-access/index.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/installations_/$installationId/accounts_/$accountId/users/": {
      "filePath": "_app/installations_/$installationId/accounts_/$accountId/users/index.lazy.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
