// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Login() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"container container-tight py-4\"><div class=\"card card-md\"><div class=\"card-body\"><h2 class=\"h2 text-center mb-4\">Login to your account</h2><form hx-post=\"/login\" hx-target=\"#content\" autocomplete=\"off\" novalidate><div class=\"mb-3\"><label class=\"form-label\">Email address</label> <input type=\"email\" name=\"email\" class=\"form-control\" placeholder=\"your@email.com\" autocomplete=\"off\"></div><div class=\"mb-2\"><label class=\"form-label\">Password</label><div class=\"input-group input-group-flat\"><input type=\"password\" name=\"password\" class=\"form-control\" placeholder=\"Your password\" autocomplete=\"off\"></div></div><div class=\"form-footer\"><button type=\"submit\" class=\"btn btn-primary w-100\">Sign in</button></div></form></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
